#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

"""
Add task instance anomaly table.

Revision ID: 438ed3578bfb
Revises: 7e8e6d53a4b2
Create Date: 2026-03-18 03:28:33.941853

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from airflow.utils.sqlalchemy import UtcDateTime

# revision identifiers, used by Alembic.
revision = "438ed3578bfb"
down_revision = "7e8e6d53a4b2"
branch_labels = None
depends_on = None
airflow_version = "3.2.0"


def upgrade():
    """Apply add task instance anomaly table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_instance_anomaly",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dag_id", sa.String(length=250), nullable=False),
        sa.Column("run_id", sa.String(length=250), nullable=False),
        sa.Column("task_id", sa.String(length=250), nullable=False),
        sa.Column("map_index", sa.Integer(), nullable=False),
        sa.Column("try_number", sa.Integer(), nullable=False),
        sa.Column("is_anomalous", sa.Boolean(), nullable=False),
        sa.Column("detector_name", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("created_at", UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", UtcDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("task_instance_anomaly_pkey")),
        sa.UniqueConstraint(
            "dag_id",
            "run_id",
            "task_id",
            "map_index",
            "try_number",
            name="uq_task_instance_anomaly_dag_run_task_map_try",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    """Unapply add task instance anomaly table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_instance_anomaly", if_exists=True)
    # ### end Alembic commands ###
